### ISSUE TITLE
Load failed. Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by XBeg9** [microsoft/DurableFunctionsMonitor#119]
Getting `Load failed. Object reference not set to an instance of an object.` error after selecting `Task hub` on `Netherite` backend deploy (used the "Deploy" button from the documentation).
Would appreciate any help around this problem

**Comment by XBeg9** [comment]
I pulled out a little bit more info, so it fails inside `DfmGetOrchestrationsFunction` with such stack trace:

```
2023-07-06T20:33:06.803 [Error] DFM failed
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.AzureStorageDurabilityProviderFactory.GetAzureStorageOrchestrationServiceSettings(String connectionName,String taskHubNameOverride) at D:\a\_work\1\s\src\WebJobs.Extensions.DurableTask\AzureStorageDurabilityProviderFactory.cs : 177
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.AzureStorageDurabilityProviderFactory.GetAzureStorageStorageProvider(DurableClientAttribute attribute) at D:\a\_work\1\s\src\WebJobs.Extensions.DurableTask\AzureStorageDurabilityProviderFactory.cs : 143
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.ContextImplementations.DurableClientFactory.<>c__DisplayClass15_0.<CreateClient>b__0(DurableClientAttribute attr) at D:\a\_work\1\s\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableClientFactory.cs : 83
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key,Func`2 valueFactory)
   at async DurableFunctionsMonitor.DotNetBackend.HttpHandlerBase.<>c__DisplayClass2_0.<HandleAuthAndErrors>b__0(??)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async DurableFunctionsMonitor.DotNetBackend.Globals.HandleErrors(HttpRequest req,ILogger log,Func`1 todo)
```

**Comment by scale-tone** [comment]
Hi @XBeg9 , did you use [this button](https://github.com/microsoft/DurableFunctionsMonitor/tree/main/custom-backends/netherite#how-to-deploy-to-azure) to deploy that instance or something else?

Because if yes, then that stack trace looks weird. It should be NetheriteStorageProvider, not AzureStorageDurabilityProvider...

**Comment by XBeg9** [comment]
@scale-tone I found the issue, our event hub name was using `snake-case` which triggered that issue, renaming it to all lowercase, without dashes fixed the issue.
