### ISSUE TITLE
Login failed. Failed to load the list of Task Hubs. Request failed with status code 401

### ISSUE THREAD

**Issue by LeastOne** [microsoft/DurableFunctionsMonitor#199]
I have a use case in which I want to deploy Durable Functions Monitor standalone in my .net8.0 isolated worker Azure Functions project. Initially getting a blank page while attempting to integrate this [Authentication issues in injected mode](https://github.com/microsoft/DurableFunctionsMonitor/issues/104) thread got me unstuck by upgrading to `DurableFunctionsMonitor.DotNetIsolated v6.5.0-beta2`.

From there I was able to deploy DFM as a part of my project and enabled AAD auth. When I log in the login requests seem to progress normally invoking `/.auth/login/aad/callback` and redirecting to `/api/durable-functions-monitor/` until it attempts `/api/durable-functions-monitor/a/p/i/task-hub-names` which fails with a `401 Unauthorized` response and causes the display of the modal reporting "Login failed. Failed to load the list of Task Hubs. Request failed with status code 401".

That's more or less as far as I've gotten. Speculatively I took a look at the function list and see `DfmGetTaskHubNamesFunction`, curiously in my deployed project it does not appear to be defined with anonymous access when viewed in the Azure Portal. If I use the available Azure template to deploy an instance of DFM standalone it works authenticating the same way but the same function definition in the Azure Portal shows its explicitly as allow anonymous.

Any ideas on any potential easy and obvious things being overlooked?

**Comment by scale-tone** [comment]
Hi @LeastOne , the quickest way to investigate would be to check the logs - for each 401 response there should be a clear explanation of what exactly went wrong.
Can you try that?

**Comment by LeastOne** [comment]
Thanks for the suggestion, here's what I find in the log ...

```
2024-06-27T05:23:05Z   [Information]   info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
2024-06-27T05:23:05Z   [Information]         Request starting HTTP/1.1 GET http://localhost:50080/api/durable-functions-monitor/a/p/i/task-hub-names - - -
2024-06-27T05:23:05Z   [Information]   info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
2024-06-27T05:23:05Z   [Information]         Executing endpoint 'DfmGetTaskHubNamesFunction'
2024-06-27T05:23:05Z   [Information]   fail: object[0]
2024-06-27T05:23:05Z   [Information]         DFM failed to authenticate request
2024-06-27T05:23:05Z   [Information]         DurableFunctionsMonitor.DotNetIsolated.DfmUnauthorizedException: No access token provided. Call is rejected.
2024-06-27T05:23:05Z   [Information]            at DurableFunctionsMonitor.DotNetIsolated.Auth.ValidateToken(String authorizationHeader)
2024-06-27T05:23:05Z   [Information]            at DurableFunctionsMonitor.DotNetIsolated.Auth.ValidateIdentityAsync(HttpRequestData request, OperationKind operationKind, DfmSettings settings, DfmExtensionPoints extensionPoints)
2024-06-27T05:23:05Z   [Information]            at DurableFunctionsMonitor.DotNetIsolated.ExtensionMethods.<>c__DisplayClass0_0.<<UseDurableFunctionsMonitor>b__1>d.MoveNext()
2024-06-27T05:23:05Z   [Error]   DFM failed to authenticate request
2024-06-27T05:23:05Z   [Information]   Executed 'Functions.DfmGetTaskHubNamesFunction' (Succeeded, Id=1df47103-6031-4a7e-93de-dc1219590c4d, Duration=116ms)
2024-06-27T05:23:05Z   [Information]   info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
2024-06-27T05:23:05Z   [Information]         Executed endpoint 'DfmGetTaskHubNamesFunction'
2024-06-27T05:23:05Z   [Information]   info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
2024-06-27T05:23:05Z   [Information]         Request finished HTTP/1.1 GET /api/durable-functions-monitor/a/p/i/task-hub-names - 401 0 - 59.2768ms
```

**Comment by scale-tone** [comment]
This means the server side thinks it is in [client-directed login flow](https://github.com/microsoft/DurableFunctionsMonitor/wiki/How-to-configure-authentication#configuring-dfmon-for-client-directed-login-flow) and the client side thinks it is in [server-directed login flow](https://github.com/microsoft/DurableFunctionsMonitor/wiki/How-to-configure-authentication#configuring-dfmon-for-server-directed-login-flow).

Can you show the `Authentication` tab of your Function App instance?

**Comment by LeastOne** [comment]
Reading other issues I was wondering if it may have been something like that. Your suggestion led me to a solution.

Here's how my function apps authentication was configured ...

![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/5291141/2c6b75b3-7d34-40e0-aacf-99b2e900f65d)

After making the following changes its working ...

- *Client secret setting name*: Remove client secret setting (after save becomes Select client secret setting name)
    - This got set automatically by Azure when I used the "Add Identity Provider" feature to select the same identity provider that was created when I used templated provided in this project.
- *Client application requirement*: `Allow requests from any application (Not recommended)`

![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/5291141/af95e164-b22e-4695-98d8-c60917465452)
